# Configuration file for TravisCI builds
language: python
python:
  - "3.9"

# These packages we only want in our CI builds
before_install:
  - python -m pip install build pytest pytest-cov

# This installs our project in the running container, convenient with PEP517 and
# setuptools (Lecture 08).  We can do this local as well, without uploading to
# PyPI first
install:
  - (python -m build --wheel && python -m pip install dist/*)

# Run the tests and create coverage reports
script:
  - (cd tests && ./run_tests.sh pytest --cov=cs107_package --cov-report=xml)

# Upload the coverage report to codecov
after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
